### ISSUE TITLE
Compile failed on rust 0.5

### ISSUE THREAD

**Issue by acertain** [drhodes/rust-ncurses#1]
```
rustc --bin ncurses.rc --test  
window.rs:8:0: 8:5 error: expected item but found `class`
window.rs:8 class Window {
            ^~~~~
make: *** [all] Error 101
```

**Comment by drhodes** [comment]
Hi, I've updated for rust 0.6. $ make;  now creates a shared object.  It won't be of much use I'm afraid, the library still has a ton of functions that need implementing.

**Comment by acertain** [comment]
Yep. I'm working on that and a better, object-oriented interface like python's curses library. Will have a pull request soon.
